main: de.bruno.village.main.Main
name: Village
version: 1.0

commands:
   home:
      description: Teleportiert dich zu deinem gesetzten zuhause
   sethome:
      description: Setzt dein zuhause an deine aktuelle Position
   recover:
      description: Stellt dein Inventart wieder her